CREATE TYPE "estado_lote" AS ENUM('Vigente', 'Vencido', 'Agotado');--> statement-breakpoint
CREATE TYPE "estado_orden_compra" AS ENUM('CRD', 'ENP', 'FNL', 'ANL');--> statement-breakpoint
CREATE TYPE "estado_orden_trabajo" AS ENUM('GENERADA', 'EN PROCESO', 'ANULADA', 'FINALIZADA');--> statement-breakpoint
CREATE TYPE "estado_pedido" AS ENUM('CREADO', 'LST', 'ANL', 'ENR', 'ENT');--> statement-breakpoint
CREATE TYPE "estado_recepcion" AS ENUM('Completa', 'Incompleta');--> statement-breakpoint
CREATE TYPE "movimiento" AS ENUM('ING', 'SLD', 'MER', 'VNC', 'TRS');--> statement-breakpoint
CREATE TYPE "rol_usuario" AS ENUM('ADMIN', 'BODEGUERO', 'DESPACHADOR', 'REPARTIDOR', 'CAJERO');--> statement-breakpoint
CREATE TYPE "tipo_caja" AS ENUM('Caja chica', 'GastosR', 'Transito');--> statement-breakpoint
CREATE TYPE "tipo_recepcion" AS ENUM('Total', 'Parcial');--> statement-breakpoint
CREATE TABLE "ALACENA" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ALACENA_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"bodega_id" integer,
	"alacena" varchar(100) NOT NULL,
	"creado_en" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "bodega" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "bodega_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"sucursal_id" integer NOT NULL,
	"bodega" varchar(100) NOT NULL UNIQUE
);
--> statement-breakpoint
CREATE TABLE "CAJA" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "CAJA_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"sucursal_id" integer,
	"tipo" "tipo_caja",
	"nombre" varchar(100)
);
--> statement-breakpoint
CREATE TABLE "categoria" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "categoria_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"categoria_id" integer NOT NULL UNIQUE,
	"descripcion" varchar(100) NOT NULL,
	"creado_en" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "cliente" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cliente_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"nombre" varchar(100) NOT NULL,
	"apellido" varchar(100) NOT NULL,
	"telefono" varchar(50) NOT NULL UNIQUE,
	"telefono_ref" varchar(50) NOT NULL UNIQUE,
	"creado_en" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "departamento" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "departamento_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"departamento" varchar(100) NOT NULL UNIQUE
);
--> statement-breakpoint
CREATE TABLE "DETALLE_ORDEN_COMPRA" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "DETALLE_ORDEN_COMPRA_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"orden_compra_id" bigint NOT NULL,
	"materia_prima_id" integer NOT NULL,
	"cantidad_solicitada" double precision NOT NULL,
	"precio_unitario" double precision NOT NULL,
	"subtotal" double precision NOT NULL
);
--> statement-breakpoint
CREATE TABLE "DETALLE_PEDIDO" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "DETALLE_PEDIDO_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"pedido_id" bigint,
	"producto_id" integer NOT NULL,
	"cantidad" double precision NOT NULL
);
--> statement-breakpoint
CREATE TABLE "direccion" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "direccion_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"cliente_id" bigint NOT NULL,
	"municipio_id" integer NOT NULL,
	"direccion" varchar(155) NOT NULL,
	"direccion2" varchar(100) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "FACTURA_COMPRA" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "FACTURA_COMPRA_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"hoja_recepcion_id" bigint,
	"serie" varchar(15) NOT NULL,
	"numero" varchar(32) NOT NULL,
	"fecha_emision" date NOT NULL,
	"total" double precision NOT NULL,
	"fecha_ingreso" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "FACTURA_VENTA" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "FACTURA_VENTA_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"pedido_id" bigint NOT NULL,
	"serie" varchar(15) NOT NULL,
	"numero" varchar(32) NOT NULL,
	"fecha_emision" timestamp DEFAULT now() NOT NULL,
	"total" double precision NOT NULL,
	"creado_en" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "GASTOS_SUCURSAL" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "GASTOS_SUCURSAL_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"caja_id" integer,
	"usuario_id" integer,
	"sucursal_id" integer,
	"monto_apertura" double precision,
	"monto_cierre_declarado" double precision,
	"monto_cierre_sistema" double precision,
	"abierto_en" timestamp,
	"cerrado_en" timestamp
);
--> statement-breakpoint
CREATE TABLE "HOJA_DESPACHO_DETALLE" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "HOJA_DESPACHO_DETALLE_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"hoja_despacho_id" bigint,
	"producto_lote_id" integer,
	"cantidad_despachada" double precision
);
--> statement-breakpoint
CREATE TABLE "HOJA_DESPACHO" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "HOJA_DESPACHO_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"pedido_id" bigint,
	"sucursal_despacho" integer,
	"despachado_en" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "HOJA_RECEPCION_DETALLE" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "HOJA_RECEPCION_DETALLE_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"hoja_recepcion_id" bigint,
	"materia_prima_id" integer,
	"cantidad_recibida" double precision NOT NULL,
	"fecha_vencimiento" timestamp DEFAULT now() NOT NULL,
	"merma" double precision,
	"saldo" double precision NOT NULL,
	"estado_recepcion" "estado_recepcion" DEFAULT 'Completa'::"estado_recepcion" NOT NULL
);
--> statement-breakpoint
CREATE TABLE "HOJA_RECEPCION" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "HOJA_RECEPCION_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"sucursal_receptora" integer,
	"orden_compra_id" bigint,
	"tipo_recepcion" "tipo_recepcion" DEFAULT 'Total'::"tipo_recepcion" NOT NULL,
	"fecha_generada" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "KARDEX_ALACENA" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "KARDEX_ALACENA_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"alacena_id" integer,
	"lote_id" bigint,
	"movimiento" "movimiento" NOT NULL,
	"cantidad" double precision NOT NULL,
	"fecha_movimiento" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "kardex_bodega" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "kardex_bodega_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"bodega_id" integer NOT NULL,
	"lote_id" bigint NOT NULL,
	"movimiento" "movimiento" NOT NULL,
	"cantidad" double precision NOT NULL,
	"fecha_movimiento" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "LIQUIDACION_REPARTIDOR" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "LIQUIDACION_REPARTIDOR_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"turno_id" bigint,
	"repartidor_id" integer,
	"monto_entregado_repartidor" double precision,
	"monto_recaudado_efectivo" double precision,
	"monto_recaudado_voucher" double precision,
	"creado_en" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "lote_materia_prima" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "lote_materia_prima_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"materia_prima_id" integer NOT NULL,
	"fecha_vencimiento" date NOT NULL,
	"cantidad_inicial" double precision NOT NULL,
	"cantidad_actual" double precision NOT NULL,
	"estado" "estado_lote" DEFAULT 'Vigente'::"estado_lote" NOT NULL,
	"creado_en" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "materia_prima" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "materia_prima_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"categoria_id" integer NOT NULL,
	"unidad_medida_id" integer NOT NULL,
	"materia_prima" varchar(150) NOT NULL,
	"es_perecedera" boolean DEFAULT false NOT NULL,
	"maneja_merma" boolean DEFAULT false NOT NULL,
	"creado_en" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "municipio" (
	"id" integer PRIMARY KEY,
	"departamento_id" integer NOT NULL,
	"municipio" varchar(100) NOT NULL UNIQUE
);
--> statement-breakpoint
CREATE TABLE "ORDEN_COMPRA" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ORDEN_COMPRA_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"proveedor_id" integer,
	"sucursal_destino" integer,
	"fecha_generada" timestamp DEFAULT now() NOT NULL,
	"estado_orden" "estado_orden_compra" DEFAULT 'CRD'::"estado_orden_compra" NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ORDEN_TRABAJO" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ORDEN_TRABAJO_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"sucursal_id" integer,
	"receta_id" integer,
	"cantidad_produccion" double precision,
	"estado" "estado_orden_trabajo"
);
--> statement-breakpoint
CREATE TABLE "PEDIDO" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "PEDIDO_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"cliente_id" bigint NOT NULL,
	"fecha_pedido" timestamp DEFAULT now() NOT NULL,
	"observaciones" varchar(255),
	"estado" "estado_pedido" DEFAULT 'CREADO'::"estado_pedido" NOT NULL
);
--> statement-breakpoint
CREATE TABLE "PRODUCTO_LOTE" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "PRODUCTO_LOTE_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"orden_id" bigint,
	"cantidad_inicial" double precision,
	"cantidad_actual" double precision,
	"estado" "estado_lote" DEFAULT 'Vigente'::"estado_lote",
	"producido_en" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "PRODUCTO" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "PRODUCTO_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"categoria_id" integer NOT NULL,
	"unidad_medida_id" integer NOT NULL,
	"producto" varchar(150) NOT NULL,
	"precio" double precision NOT NULL
);
--> statement-breakpoint
CREATE TABLE "PROVEEDOR" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "PROVEEDOR_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"no_nit" varchar(13) NOT NULL UNIQUE,
	"proveedor" varchar(150) NOT NULL UNIQUE,
	"direccion" varchar(255)
);
--> statement-breakpoint
CREATE TABLE "RECETA_DETALLE" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "RECETA_DETALLE_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"receta_id" integer,
	"materia_prima_id" integer,
	"cantidad_necesaria" double precision NOT NULL
);
--> statement-breakpoint
CREATE TABLE "RECETA" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "RECETA_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"producto_id" integer,
	"nombre" varchar(150) NOT NULL,
	"cantidad_lote" double precision NOT NULL,
	"creada_en" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "STOCK_ALACENA" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "STOCK_ALACENA_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"alacena_id" integer,
	"lote_id" bigint
);
--> statement-breakpoint
CREATE TABLE "stock_bodega" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "stock_bodega_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"bodega_id" integer NOT NULL,
	"lote_id" bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "sucursal" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sucursal_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"municipio_id" integer NOT NULL,
	"sucursal" varchar(100) NOT NULL UNIQUE,
	"direccion" varchar(255)
);
--> statement-breakpoint
CREATE TABLE "TURNO_DESPACHADOR" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "TURNO_DESPACHADOR_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"caja_id" integer,
	"usuario_id" integer,
	"administrador_id" integer,
	"monto_apertura" double precision,
	"monto_cierre_declarado" double precision,
	"monto_cierre_sistema" double precision,
	"abierto_en" timestamp,
	"cerrado_en" timestamp
);
--> statement-breakpoint
CREATE TABLE "unidad_medida" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "unidad_medida_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"unidad" varchar(50) NOT NULL,
	"abreviatura" varchar(4) NOT NULL UNIQUE,
	"creado_en" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "USUARIO" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "USUARIO_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"usuario" varchar(50),
	"correo_electronico" varchar(255),
	"contrasenia" varchar(50),
	"rol_usuario" "rol_usuario" NOT NULL,
	"creado_en" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "ALACENA" ADD CONSTRAINT "ALACENA_bodega_id_bodega_id_fkey" FOREIGN KEY ("bodega_id") REFERENCES "bodega"("id");--> statement-breakpoint
ALTER TABLE "bodega" ADD CONSTRAINT "bodega_sucursal_id_sucursal_id_fkey" FOREIGN KEY ("sucursal_id") REFERENCES "sucursal"("id");--> statement-breakpoint
ALTER TABLE "CAJA" ADD CONSTRAINT "CAJA_sucursal_id_sucursal_id_fkey" FOREIGN KEY ("sucursal_id") REFERENCES "sucursal"("id");--> statement-breakpoint
ALTER TABLE "DETALLE_ORDEN_COMPRA" ADD CONSTRAINT "DETALLE_ORDEN_COMPRA_orden_compra_id_ORDEN_COMPRA_id_fkey" FOREIGN KEY ("orden_compra_id") REFERENCES "ORDEN_COMPRA"("id");--> statement-breakpoint
ALTER TABLE "DETALLE_ORDEN_COMPRA" ADD CONSTRAINT "DETALLE_ORDEN_COMPRA_materia_prima_id_materia_prima_id_fkey" FOREIGN KEY ("materia_prima_id") REFERENCES "materia_prima"("id");--> statement-breakpoint
ALTER TABLE "DETALLE_PEDIDO" ADD CONSTRAINT "DETALLE_PEDIDO_pedido_id_PEDIDO_id_fkey" FOREIGN KEY ("pedido_id") REFERENCES "PEDIDO"("id");--> statement-breakpoint
ALTER TABLE "DETALLE_PEDIDO" ADD CONSTRAINT "DETALLE_PEDIDO_producto_id_PRODUCTO_id_fkey" FOREIGN KEY ("producto_id") REFERENCES "PRODUCTO"("id");--> statement-breakpoint
ALTER TABLE "direccion" ADD CONSTRAINT "direccion_cliente_id_cliente_id_fkey" FOREIGN KEY ("cliente_id") REFERENCES "cliente"("id");--> statement-breakpoint
ALTER TABLE "direccion" ADD CONSTRAINT "direccion_municipio_id_municipio_id_fkey" FOREIGN KEY ("municipio_id") REFERENCES "municipio"("id");--> statement-breakpoint
ALTER TABLE "FACTURA_COMPRA" ADD CONSTRAINT "FACTURA_COMPRA_hoja_recepcion_id_HOJA_RECEPCION_id_fkey" FOREIGN KEY ("hoja_recepcion_id") REFERENCES "HOJA_RECEPCION"("id");--> statement-breakpoint
ALTER TABLE "FACTURA_VENTA" ADD CONSTRAINT "FACTURA_VENTA_pedido_id_PEDIDO_id_fkey" FOREIGN KEY ("pedido_id") REFERENCES "PEDIDO"("id");--> statement-breakpoint
ALTER TABLE "GASTOS_SUCURSAL" ADD CONSTRAINT "GASTOS_SUCURSAL_caja_id_CAJA_id_fkey" FOREIGN KEY ("caja_id") REFERENCES "CAJA"("id");--> statement-breakpoint
ALTER TABLE "GASTOS_SUCURSAL" ADD CONSTRAINT "GASTOS_SUCURSAL_usuario_id_USUARIO_id_fkey" FOREIGN KEY ("usuario_id") REFERENCES "USUARIO"("id");--> statement-breakpoint
ALTER TABLE "GASTOS_SUCURSAL" ADD CONSTRAINT "GASTOS_SUCURSAL_sucursal_id_sucursal_id_fkey" FOREIGN KEY ("sucursal_id") REFERENCES "sucursal"("id");--> statement-breakpoint
ALTER TABLE "HOJA_DESPACHO_DETALLE" ADD CONSTRAINT "HOJA_DESPACHO_DETALLE_hoja_despacho_id_HOJA_DESPACHO_id_fkey" FOREIGN KEY ("hoja_despacho_id") REFERENCES "HOJA_DESPACHO"("id");--> statement-breakpoint
ALTER TABLE "HOJA_DESPACHO_DETALLE" ADD CONSTRAINT "HOJA_DESPACHO_DETALLE_producto_lote_id_PRODUCTO_LOTE_id_fkey" FOREIGN KEY ("producto_lote_id") REFERENCES "PRODUCTO_LOTE"("id");--> statement-breakpoint
ALTER TABLE "HOJA_DESPACHO" ADD CONSTRAINT "HOJA_DESPACHO_pedido_id_PEDIDO_id_fkey" FOREIGN KEY ("pedido_id") REFERENCES "PEDIDO"("id");--> statement-breakpoint
ALTER TABLE "HOJA_DESPACHO" ADD CONSTRAINT "HOJA_DESPACHO_sucursal_despacho_sucursal_id_fkey" FOREIGN KEY ("sucursal_despacho") REFERENCES "sucursal"("id");--> statement-breakpoint
ALTER TABLE "HOJA_RECEPCION_DETALLE" ADD CONSTRAINT "HOJA_RECEPCION_DETALLE_hoja_recepcion_id_HOJA_RECEPCION_id_fkey" FOREIGN KEY ("hoja_recepcion_id") REFERENCES "HOJA_RECEPCION"("id");--> statement-breakpoint
ALTER TABLE "HOJA_RECEPCION_DETALLE" ADD CONSTRAINT "HOJA_RECEPCION_DETALLE_materia_prima_id_materia_prima_id_fkey" FOREIGN KEY ("materia_prima_id") REFERENCES "materia_prima"("id");--> statement-breakpoint
ALTER TABLE "HOJA_RECEPCION" ADD CONSTRAINT "HOJA_RECEPCION_sucursal_receptora_sucursal_id_fkey" FOREIGN KEY ("sucursal_receptora") REFERENCES "sucursal"("id");--> statement-breakpoint
ALTER TABLE "HOJA_RECEPCION" ADD CONSTRAINT "HOJA_RECEPCION_orden_compra_id_ORDEN_COMPRA_id_fkey" FOREIGN KEY ("orden_compra_id") REFERENCES "ORDEN_COMPRA"("id");--> statement-breakpoint
ALTER TABLE "KARDEX_ALACENA" ADD CONSTRAINT "KARDEX_ALACENA_alacena_id_ALACENA_id_fkey" FOREIGN KEY ("alacena_id") REFERENCES "ALACENA"("id");--> statement-breakpoint
ALTER TABLE "KARDEX_ALACENA" ADD CONSTRAINT "KARDEX_ALACENA_lote_id_lote_materia_prima_id_fkey" FOREIGN KEY ("lote_id") REFERENCES "lote_materia_prima"("id");--> statement-breakpoint
ALTER TABLE "kardex_bodega" ADD CONSTRAINT "kardex_bodega_bodega_id_bodega_id_fkey" FOREIGN KEY ("bodega_id") REFERENCES "bodega"("id");--> statement-breakpoint
ALTER TABLE "kardex_bodega" ADD CONSTRAINT "kardex_bodega_lote_id_lote_materia_prima_id_fkey" FOREIGN KEY ("lote_id") REFERENCES "lote_materia_prima"("id");--> statement-breakpoint
ALTER TABLE "LIQUIDACION_REPARTIDOR" ADD CONSTRAINT "LIQUIDACION_REPARTIDOR_turno_id_TURNO_DESPACHADOR_id_fkey" FOREIGN KEY ("turno_id") REFERENCES "TURNO_DESPACHADOR"("id");--> statement-breakpoint
ALTER TABLE "LIQUIDACION_REPARTIDOR" ADD CONSTRAINT "LIQUIDACION_REPARTIDOR_repartidor_id_USUARIO_id_fkey" FOREIGN KEY ("repartidor_id") REFERENCES "USUARIO"("id");--> statement-breakpoint
ALTER TABLE "lote_materia_prima" ADD CONSTRAINT "lote_materia_prima_materia_prima_id_materia_prima_id_fkey" FOREIGN KEY ("materia_prima_id") REFERENCES "materia_prima"("id");--> statement-breakpoint
ALTER TABLE "materia_prima" ADD CONSTRAINT "materia_prima_categoria_id_categoria_id_fkey" FOREIGN KEY ("categoria_id") REFERENCES "categoria"("id");--> statement-breakpoint
ALTER TABLE "materia_prima" ADD CONSTRAINT "materia_prima_unidad_medida_id_unidad_medida_id_fkey" FOREIGN KEY ("unidad_medida_id") REFERENCES "unidad_medida"("id");--> statement-breakpoint
ALTER TABLE "municipio" ADD CONSTRAINT "municipio_departamento_id_departamento_id_fkey" FOREIGN KEY ("departamento_id") REFERENCES "departamento"("id");--> statement-breakpoint
ALTER TABLE "ORDEN_COMPRA" ADD CONSTRAINT "ORDEN_COMPRA_proveedor_id_PROVEEDOR_id_fkey" FOREIGN KEY ("proveedor_id") REFERENCES "PROVEEDOR"("id");--> statement-breakpoint
ALTER TABLE "ORDEN_COMPRA" ADD CONSTRAINT "ORDEN_COMPRA_sucursal_destino_sucursal_id_fkey" FOREIGN KEY ("sucursal_destino") REFERENCES "sucursal"("id");--> statement-breakpoint
ALTER TABLE "ORDEN_TRABAJO" ADD CONSTRAINT "ORDEN_TRABAJO_sucursal_id_sucursal_id_fkey" FOREIGN KEY ("sucursal_id") REFERENCES "sucursal"("id");--> statement-breakpoint
ALTER TABLE "ORDEN_TRABAJO" ADD CONSTRAINT "ORDEN_TRABAJO_receta_id_RECETA_id_fkey" FOREIGN KEY ("receta_id") REFERENCES "RECETA"("id");--> statement-breakpoint
ALTER TABLE "PEDIDO" ADD CONSTRAINT "PEDIDO_cliente_id_cliente_id_fkey" FOREIGN KEY ("cliente_id") REFERENCES "cliente"("id");--> statement-breakpoint
ALTER TABLE "PRODUCTO_LOTE" ADD CONSTRAINT "PRODUCTO_LOTE_orden_id_ORDEN_TRABAJO_id_fkey" FOREIGN KEY ("orden_id") REFERENCES "ORDEN_TRABAJO"("id");--> statement-breakpoint
ALTER TABLE "PRODUCTO" ADD CONSTRAINT "PRODUCTO_categoria_id_categoria_id_fkey" FOREIGN KEY ("categoria_id") REFERENCES "categoria"("id");--> statement-breakpoint
ALTER TABLE "PRODUCTO" ADD CONSTRAINT "PRODUCTO_unidad_medida_id_unidad_medida_id_fkey" FOREIGN KEY ("unidad_medida_id") REFERENCES "unidad_medida"("id");--> statement-breakpoint
ALTER TABLE "RECETA_DETALLE" ADD CONSTRAINT "RECETA_DETALLE_receta_id_RECETA_id_fkey" FOREIGN KEY ("receta_id") REFERENCES "RECETA"("id");--> statement-breakpoint
ALTER TABLE "RECETA_DETALLE" ADD CONSTRAINT "RECETA_DETALLE_materia_prima_id_materia_prima_id_fkey" FOREIGN KEY ("materia_prima_id") REFERENCES "materia_prima"("id");--> statement-breakpoint
ALTER TABLE "RECETA" ADD CONSTRAINT "RECETA_producto_id_PRODUCTO_id_fkey" FOREIGN KEY ("producto_id") REFERENCES "PRODUCTO"("id");--> statement-breakpoint
ALTER TABLE "STOCK_ALACENA" ADD CONSTRAINT "STOCK_ALACENA_alacena_id_ALACENA_id_fkey" FOREIGN KEY ("alacena_id") REFERENCES "ALACENA"("id");--> statement-breakpoint
ALTER TABLE "STOCK_ALACENA" ADD CONSTRAINT "STOCK_ALACENA_lote_id_lote_materia_prima_id_fkey" FOREIGN KEY ("lote_id") REFERENCES "lote_materia_prima"("id");--> statement-breakpoint
ALTER TABLE "stock_bodega" ADD CONSTRAINT "stock_bodega_bodega_id_bodega_id_fkey" FOREIGN KEY ("bodega_id") REFERENCES "bodega"("id");--> statement-breakpoint
ALTER TABLE "stock_bodega" ADD CONSTRAINT "stock_bodega_lote_id_lote_materia_prima_id_fkey" FOREIGN KEY ("lote_id") REFERENCES "lote_materia_prima"("id");--> statement-breakpoint
ALTER TABLE "sucursal" ADD CONSTRAINT "sucursal_municipio_id_municipio_id_fkey" FOREIGN KEY ("municipio_id") REFERENCES "municipio"("id");--> statement-breakpoint
ALTER TABLE "TURNO_DESPACHADOR" ADD CONSTRAINT "TURNO_DESPACHADOR_caja_id_CAJA_id_fkey" FOREIGN KEY ("caja_id") REFERENCES "CAJA"("id");--> statement-breakpoint
ALTER TABLE "TURNO_DESPACHADOR" ADD CONSTRAINT "TURNO_DESPACHADOR_usuario_id_USUARIO_id_fkey" FOREIGN KEY ("usuario_id") REFERENCES "USUARIO"("id");--> statement-breakpoint
ALTER TABLE "TURNO_DESPACHADOR" ADD CONSTRAINT "TURNO_DESPACHADOR_administrador_id_sucursal_id_fkey" FOREIGN KEY ("administrador_id") REFERENCES "sucursal"("id");