CREATE TYPE "estado_lote" AS ENUM('VIGENTE', 'VENCIDO', 'AGOTADO');--> statement-breakpoint
CREATE TYPE "estado_orden_compra" AS ENUM('CREADA', 'EN_PROCESO', 'FINALIZADO', 'ANULADO');--> statement-breakpoint
CREATE TYPE "estado_orden_trabajo" AS ENUM('GENERADA', 'EN_PROCESO', 'ANULADA', 'FINALIZADA');--> statement-breakpoint
CREATE TYPE "estado_pedido" AS ENUM('CREADO', 'LISTO', 'ANULADO', 'EN_RUTA', 'ENTREGADO');--> statement-breakpoint
CREATE TYPE "estado_recepcion" AS ENUM('COMPLETA', 'INCOMPLETA');--> statement-breakpoint
CREATE TYPE "estado_solicitud_insumo" AS ENUM('PENDIENTE', 'ENVIADA', 'RECIBIDA', 'CANCELADA');--> statement-breakpoint
CREATE TYPE "movimiento" AS ENUM('INGRESO', 'SALIDA', 'MERMA', 'VENCIMIENTO', 'TRASLADO');--> statement-breakpoint
CREATE TYPE "rol_usuario" AS ENUM('ADMIN', 'BODEGUERO', 'DESPACHADOR', 'REPARTIDOR', 'CAJERO');--> statement-breakpoint
CREATE TYPE "tipo_caja" AS ENUM('CAJA_CHICA', 'GASTOS_REPRESENTACION', 'TRANSITO');--> statement-breakpoint
CREATE TYPE "tipo_recepcion" AS ENUM('TOTAL', 'PARCIAL');--> statement-breakpoint
CREATE TABLE "ALACENA" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ALACENA_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"bodega_id" integer,
	"alacena" varchar(100) NOT NULL,
	"creado_en" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "BODEGA" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "BODEGA_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"sucursal_id" integer NOT NULL,
	"bodega" varchar(100) NOT NULL UNIQUE
);
--> statement-breakpoint
CREATE TABLE "CAJA" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "CAJA_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"sucursal_id" integer,
	"tipo" "tipo_caja",
	"nombre" varchar(100)
);
--> statement-breakpoint
CREATE TABLE "CATEGORIA" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "CATEGORIA_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"categoria_id" integer NOT NULL UNIQUE,
	"descripcion" varchar(100) NOT NULL,
	"creado_en" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "CLIENTE" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "CLIENTE_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"nombre" varchar(100) NOT NULL,
	"apellido" varchar(100) NOT NULL,
	"telefono" varchar(50) NOT NULL UNIQUE,
	"telefono_ref" varchar(50) NOT NULL UNIQUE,
	"creado_en" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "DEPARTAMENTO" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "DEPARTAMENTO_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"departamento" varchar(100) NOT NULL UNIQUE
);
--> statement-breakpoint
CREATE TABLE "DETALLE_ORDEN_COMPRA" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "DETALLE_ORDEN_COMPRA_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"orden_compra_id" bigint NOT NULL,
	"materia_prima_id" integer NOT NULL,
	"cantidad_solicitada" double precision NOT NULL,
	"precio_unitario" double precision NOT NULL,
	"subtotal" double precision NOT NULL
);
--> statement-breakpoint
CREATE TABLE "DETALLE_PEDIDO" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "DETALLE_PEDIDO_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"pedido_id" bigint,
	"producto_id" integer NOT NULL,
	"precio_unitario" double precision DEFAULT 0 NOT NULL,
	"cantidad" double precision NOT NULL
);
--> statement-breakpoint
CREATE TABLE "DETALLE_SOLICITUD_INSUMO" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "DETALLE_SOLICITUD_INSUMO_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"solicitud_id" bigint NOT NULL,
	"materia_prima_id" integer NOT NULL,
	"cantidad_solicitada" double precision NOT NULL,
	"cantidad_recibida" double precision
);
--> statement-breakpoint
CREATE TABLE "DIRECCION" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "DIRECCION_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"cliente_id" bigint NOT NULL,
	"municipio_id" integer NOT NULL,
	"direccion" varchar(155) NOT NULL,
	"direccion2" varchar(100) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "FACTURA_COMPRA" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "FACTURA_COMPRA_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"hoja_recepcion_id" bigint,
	"serie" varchar(15) NOT NULL,
	"numero" varchar(32) NOT NULL,
	"fecha_emision" date NOT NULL,
	"total" double precision NOT NULL,
	"fecha_ingreso" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "FACTURA_VENTA" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "FACTURA_VENTA_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"pedido_id" bigint NOT NULL,
	"serie" varchar(15) NOT NULL,
	"numero" varchar(32) NOT NULL,
	"fecha_emision" timestamp DEFAULT now() NOT NULL,
	"total" double precision NOT NULL,
	"creado_en" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "GASTOS_SUCURSAL" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "GASTOS_SUCURSAL_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"caja_id" integer,
	"usuario_id" integer,
	"sucursal_id" integer,
	"monto_apertura" double precision,
	"monto_cierre_declarado" double precision,
	"monto_cierre_sistema" double precision,
	"abierto_en" timestamp,
	"cerrado_en" timestamp
);
--> statement-breakpoint
CREATE TABLE "HOJA_DESPACHO_DETALLE" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "HOJA_DESPACHO_DETALLE_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"hoja_despacho_id" bigint,
	"producto_lote_id" integer,
	"cantidad_despachada" double precision
);
--> statement-breakpoint
CREATE TABLE "HOJA_DESPACHO" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "HOJA_DESPACHO_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"pedido_id" bigint,
	"sucursal_despacho" integer,
	"despachado_en" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "HOJA_RECEPCION_DETALLE" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "HOJA_RECEPCION_DETALLE_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"hoja_recepcion_id" bigint,
	"materia_prima_id" integer,
	"cantidad_recibida" double precision NOT NULL,
	"fecha_vencimiento" timestamp DEFAULT now() NOT NULL,
	"merma" double precision,
	"saldo" double precision NOT NULL,
	"estado_recepcion" "estado_recepcion" DEFAULT 'COMPLETA'::"estado_recepcion" NOT NULL
);
--> statement-breakpoint
CREATE TABLE "HOJA_RECEPCION" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "HOJA_RECEPCION_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"sucursal_receptora" integer,
	"orden_compra_id" bigint,
	"tipo_recepcion" "tipo_recepcion" DEFAULT 'TOTAL'::"tipo_recepcion" NOT NULL,
	"fecha_generada" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "KARDEX_ALACENA" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "KARDEX_ALACENA_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"alacena_id" integer,
	"lote_id" bigint,
	"movimiento" "movimiento" NOT NULL,
	"cantidad" double precision NOT NULL,
	"fecha_movimiento" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "KARDEX_BODEGA" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "KARDEX_BODEGA_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"bodega_id" integer NOT NULL,
	"lote_id" bigint NOT NULL,
	"movimiento" "movimiento" NOT NULL,
	"cantidad" double precision NOT NULL,
	"fecha_movimiento" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "LIQUIDACION_REPARTIDOR" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "LIQUIDACION_REPARTIDOR_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"turno_id" bigint,
	"repartidor_id" integer,
	"monto_entregado_repartidor" double precision,
	"monto_recaudado_efectivo" double precision,
	"monto_recaudado_voucher" double precision,
	"creado_en" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "LOTE_MATERIA_PRIMA" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "LOTE_MATERIA_PRIMA_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"materia_prima_id" integer NOT NULL,
	"fecha_vencimiento" date NOT NULL,
	"cantidad_inicial" double precision NOT NULL,
	"cantidad_actual" double precision NOT NULL,
	"estado" "estado_lote" DEFAULT 'VIGENTE'::"estado_lote" NOT NULL,
	"creado_en" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "MATERIA_PRIMA" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "MATERIA_PRIMA_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"categoria_id" integer NOT NULL,
	"unidad_medida_id" integer NOT NULL,
	"materia_prima" varchar(150) NOT NULL,
	"es_perecedera" boolean DEFAULT false NOT NULL,
	"maneja_merma" boolean DEFAULT false NOT NULL,
	"creado_en" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "MUNICIPIO" (
	"id" integer PRIMARY KEY,
	"departamento_id" integer NOT NULL,
	"municipio" varchar(100) NOT NULL UNIQUE
);
--> statement-breakpoint
CREATE TABLE "ORDEN_COMPRA" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ORDEN_COMPRA_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"proveedor_id" integer,
	"sucursal_destino" integer,
	"fecha_generada" timestamp DEFAULT now() NOT NULL,
	"estado_orden" "estado_orden_compra" DEFAULT 'CREADA'::"estado_orden_compra" NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ORDEN_TRABAJO" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ORDEN_TRABAJO_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"sucursal_id" integer,
	"receta_id" integer,
	"cantidad_produccion" double precision,
	"estado" "estado_orden_trabajo"
);
--> statement-breakpoint
CREATE TABLE "PEDIDO" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "PEDIDO_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"cliente_id" bigint NOT NULL,
	"fecha_pedido" timestamp DEFAULT now() NOT NULL,
	"observaciones" varchar(255),
	"total" double precision DEFAULT 0 NOT NULL,
	"estado" "estado_pedido" DEFAULT 'CREADO'::"estado_pedido" NOT NULL
);
--> statement-breakpoint
CREATE TABLE "PRODUCTO_LOTE" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "PRODUCTO_LOTE_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"orden_id" bigint,
	"cantidad_inicial" double precision,
	"cantidad_actual" double precision,
	"estado" "estado_lote" DEFAULT 'VIGENTE'::"estado_lote",
	"producido_en" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "PRODUCTO" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "PRODUCTO_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"categoria_id" integer NOT NULL,
	"unidad_medida_id" integer NOT NULL,
	"producto" varchar(150) NOT NULL,
	"precio" double precision NOT NULL
);
--> statement-breakpoint
CREATE TABLE "PROVEEDOR" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "PROVEEDOR_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"no_nit" varchar(13) NOT NULL UNIQUE,
	"proveedor" varchar(150) NOT NULL UNIQUE,
	"direccion" varchar(255)
);
--> statement-breakpoint
CREATE TABLE "RECETA_DETALLE" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "RECETA_DETALLE_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"receta_id" integer,
	"materia_prima_id" integer,
	"cantidad_necesaria" double precision NOT NULL
);
--> statement-breakpoint
CREATE TABLE "RECETA" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "RECETA_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"producto_id" integer,
	"nombre" varchar(150) NOT NULL,
	"cantidad_lote" double precision NOT NULL,
	"creada_en" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "SOLICITUD_INSUMO" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "SOLICITUD_INSUMO_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"sucursal_id" integer,
	"solicitado_por" integer,
	"estado" "estado_solicitud_insumo" DEFAULT 'PENDIENTE'::"estado_solicitud_insumo" NOT NULL,
	"fecha_solicitud" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "STOCK_ALACENA" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "STOCK_ALACENA_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"alacena_id" integer,
	"lote_id" bigint
);
--> statement-breakpoint
CREATE TABLE "STOCK_BODEGA" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "STOCK_BODEGA_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"bodega_id" integer NOT NULL,
	"lote_id" bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "SUCURSAL" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "SUCURSAL_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"municipio_id" integer NOT NULL,
	"sucursal" varchar(100) NOT NULL UNIQUE,
	"direccion" varchar(255)
);
--> statement-breakpoint
CREATE TABLE "TURNO_DESPACHADOR" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "TURNO_DESPACHADOR_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"caja_id" integer,
	"usuario_id" integer,
	"administrador_id" integer,
	"monto_apertura" double precision,
	"monto_cierre_declarado" double precision,
	"monto_cierre_sistema" double precision,
	"abierto_en" timestamp,
	"cerrado_en" timestamp
);
--> statement-breakpoint
CREATE TABLE "UNIDAD_MEDIDA" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "UNIDAD_MEDIDA_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"unidad" varchar(50) NOT NULL,
	"abreviatura" varchar(4) NOT NULL UNIQUE,
	"creado_en" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "USUARIO" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "USUARIO_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"usuario" varchar(50),
	"correo_electronico" varchar(255),
	"contrasenia" varchar(50),
	"rol_usuario" "rol_usuario" NOT NULL,
	"creado_en" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "ALACENA" ADD CONSTRAINT "ALACENA_bodega_id_BODEGA_id_fkey" FOREIGN KEY ("bodega_id") REFERENCES "BODEGA"("id");--> statement-breakpoint
ALTER TABLE "BODEGA" ADD CONSTRAINT "BODEGA_sucursal_id_SUCURSAL_id_fkey" FOREIGN KEY ("sucursal_id") REFERENCES "SUCURSAL"("id");--> statement-breakpoint
ALTER TABLE "CAJA" ADD CONSTRAINT "CAJA_sucursal_id_SUCURSAL_id_fkey" FOREIGN KEY ("sucursal_id") REFERENCES "SUCURSAL"("id");--> statement-breakpoint
ALTER TABLE "DETALLE_ORDEN_COMPRA" ADD CONSTRAINT "DETALLE_ORDEN_COMPRA_orden_compra_id_ORDEN_COMPRA_id_fkey" FOREIGN KEY ("orden_compra_id") REFERENCES "ORDEN_COMPRA"("id");--> statement-breakpoint
ALTER TABLE "DETALLE_ORDEN_COMPRA" ADD CONSTRAINT "DETALLE_ORDEN_COMPRA_materia_prima_id_MATERIA_PRIMA_id_fkey" FOREIGN KEY ("materia_prima_id") REFERENCES "MATERIA_PRIMA"("id");--> statement-breakpoint
ALTER TABLE "DETALLE_PEDIDO" ADD CONSTRAINT "DETALLE_PEDIDO_pedido_id_PEDIDO_id_fkey" FOREIGN KEY ("pedido_id") REFERENCES "PEDIDO"("id");--> statement-breakpoint
ALTER TABLE "DETALLE_PEDIDO" ADD CONSTRAINT "DETALLE_PEDIDO_producto_id_PRODUCTO_id_fkey" FOREIGN KEY ("producto_id") REFERENCES "PRODUCTO"("id");--> statement-breakpoint
ALTER TABLE "DETALLE_SOLICITUD_INSUMO" ADD CONSTRAINT "DETALLE_SOLICITUD_INSUMO_solicitud_id_SOLICITUD_INSUMO_id_fkey" FOREIGN KEY ("solicitud_id") REFERENCES "SOLICITUD_INSUMO"("id");--> statement-breakpoint
ALTER TABLE "DETALLE_SOLICITUD_INSUMO" ADD CONSTRAINT "DETALLE_SOLICITUD_INSUMO_materia_prima_id_MATERIA_PRIMA_id_fkey" FOREIGN KEY ("materia_prima_id") REFERENCES "MATERIA_PRIMA"("id");--> statement-breakpoint
ALTER TABLE "DIRECCION" ADD CONSTRAINT "DIRECCION_cliente_id_CLIENTE_id_fkey" FOREIGN KEY ("cliente_id") REFERENCES "CLIENTE"("id");--> statement-breakpoint
ALTER TABLE "DIRECCION" ADD CONSTRAINT "DIRECCION_municipio_id_MUNICIPIO_id_fkey" FOREIGN KEY ("municipio_id") REFERENCES "MUNICIPIO"("id");--> statement-breakpoint
ALTER TABLE "FACTURA_COMPRA" ADD CONSTRAINT "FACTURA_COMPRA_hoja_recepcion_id_HOJA_RECEPCION_id_fkey" FOREIGN KEY ("hoja_recepcion_id") REFERENCES "HOJA_RECEPCION"("id");--> statement-breakpoint
ALTER TABLE "FACTURA_VENTA" ADD CONSTRAINT "FACTURA_VENTA_pedido_id_PEDIDO_id_fkey" FOREIGN KEY ("pedido_id") REFERENCES "PEDIDO"("id");--> statement-breakpoint
ALTER TABLE "GASTOS_SUCURSAL" ADD CONSTRAINT "GASTOS_SUCURSAL_caja_id_CAJA_id_fkey" FOREIGN KEY ("caja_id") REFERENCES "CAJA"("id");--> statement-breakpoint
ALTER TABLE "GASTOS_SUCURSAL" ADD CONSTRAINT "GASTOS_SUCURSAL_usuario_id_USUARIO_id_fkey" FOREIGN KEY ("usuario_id") REFERENCES "USUARIO"("id");--> statement-breakpoint
ALTER TABLE "GASTOS_SUCURSAL" ADD CONSTRAINT "GASTOS_SUCURSAL_sucursal_id_SUCURSAL_id_fkey" FOREIGN KEY ("sucursal_id") REFERENCES "SUCURSAL"("id");--> statement-breakpoint
ALTER TABLE "HOJA_DESPACHO_DETALLE" ADD CONSTRAINT "HOJA_DESPACHO_DETALLE_hoja_despacho_id_HOJA_DESPACHO_id_fkey" FOREIGN KEY ("hoja_despacho_id") REFERENCES "HOJA_DESPACHO"("id");--> statement-breakpoint
ALTER TABLE "HOJA_DESPACHO_DETALLE" ADD CONSTRAINT "HOJA_DESPACHO_DETALLE_producto_lote_id_PRODUCTO_LOTE_id_fkey" FOREIGN KEY ("producto_lote_id") REFERENCES "PRODUCTO_LOTE"("id");--> statement-breakpoint
ALTER TABLE "HOJA_DESPACHO" ADD CONSTRAINT "HOJA_DESPACHO_pedido_id_PEDIDO_id_fkey" FOREIGN KEY ("pedido_id") REFERENCES "PEDIDO"("id");--> statement-breakpoint
ALTER TABLE "HOJA_DESPACHO" ADD CONSTRAINT "HOJA_DESPACHO_sucursal_despacho_SUCURSAL_id_fkey" FOREIGN KEY ("sucursal_despacho") REFERENCES "SUCURSAL"("id");--> statement-breakpoint
ALTER TABLE "HOJA_RECEPCION_DETALLE" ADD CONSTRAINT "HOJA_RECEPCION_DETALLE_hoja_recepcion_id_HOJA_RECEPCION_id_fkey" FOREIGN KEY ("hoja_recepcion_id") REFERENCES "HOJA_RECEPCION"("id");--> statement-breakpoint
ALTER TABLE "HOJA_RECEPCION_DETALLE" ADD CONSTRAINT "HOJA_RECEPCION_DETALLE_materia_prima_id_MATERIA_PRIMA_id_fkey" FOREIGN KEY ("materia_prima_id") REFERENCES "MATERIA_PRIMA"("id");--> statement-breakpoint
ALTER TABLE "HOJA_RECEPCION" ADD CONSTRAINT "HOJA_RECEPCION_sucursal_receptora_SUCURSAL_id_fkey" FOREIGN KEY ("sucursal_receptora") REFERENCES "SUCURSAL"("id");--> statement-breakpoint
ALTER TABLE "HOJA_RECEPCION" ADD CONSTRAINT "HOJA_RECEPCION_orden_compra_id_ORDEN_COMPRA_id_fkey" FOREIGN KEY ("orden_compra_id") REFERENCES "ORDEN_COMPRA"("id");--> statement-breakpoint
ALTER TABLE "KARDEX_ALACENA" ADD CONSTRAINT "KARDEX_ALACENA_alacena_id_ALACENA_id_fkey" FOREIGN KEY ("alacena_id") REFERENCES "ALACENA"("id");--> statement-breakpoint
ALTER TABLE "KARDEX_ALACENA" ADD CONSTRAINT "KARDEX_ALACENA_lote_id_LOTE_MATERIA_PRIMA_id_fkey" FOREIGN KEY ("lote_id") REFERENCES "LOTE_MATERIA_PRIMA"("id");--> statement-breakpoint
ALTER TABLE "KARDEX_BODEGA" ADD CONSTRAINT "KARDEX_BODEGA_bodega_id_BODEGA_id_fkey" FOREIGN KEY ("bodega_id") REFERENCES "BODEGA"("id");--> statement-breakpoint
ALTER TABLE "KARDEX_BODEGA" ADD CONSTRAINT "KARDEX_BODEGA_lote_id_LOTE_MATERIA_PRIMA_id_fkey" FOREIGN KEY ("lote_id") REFERENCES "LOTE_MATERIA_PRIMA"("id");--> statement-breakpoint
ALTER TABLE "LIQUIDACION_REPARTIDOR" ADD CONSTRAINT "LIQUIDACION_REPARTIDOR_turno_id_TURNO_DESPACHADOR_id_fkey" FOREIGN KEY ("turno_id") REFERENCES "TURNO_DESPACHADOR"("id");--> statement-breakpoint
ALTER TABLE "LIQUIDACION_REPARTIDOR" ADD CONSTRAINT "LIQUIDACION_REPARTIDOR_repartidor_id_USUARIO_id_fkey" FOREIGN KEY ("repartidor_id") REFERENCES "USUARIO"("id");--> statement-breakpoint
ALTER TABLE "LOTE_MATERIA_PRIMA" ADD CONSTRAINT "LOTE_MATERIA_PRIMA_materia_prima_id_MATERIA_PRIMA_id_fkey" FOREIGN KEY ("materia_prima_id") REFERENCES "MATERIA_PRIMA"("id");--> statement-breakpoint
ALTER TABLE "MATERIA_PRIMA" ADD CONSTRAINT "MATERIA_PRIMA_categoria_id_CATEGORIA_id_fkey" FOREIGN KEY ("categoria_id") REFERENCES "CATEGORIA"("id");--> statement-breakpoint
ALTER TABLE "MATERIA_PRIMA" ADD CONSTRAINT "MATERIA_PRIMA_unidad_medida_id_UNIDAD_MEDIDA_id_fkey" FOREIGN KEY ("unidad_medida_id") REFERENCES "UNIDAD_MEDIDA"("id");--> statement-breakpoint
ALTER TABLE "MUNICIPIO" ADD CONSTRAINT "MUNICIPIO_departamento_id_DEPARTAMENTO_id_fkey" FOREIGN KEY ("departamento_id") REFERENCES "DEPARTAMENTO"("id");--> statement-breakpoint
ALTER TABLE "ORDEN_COMPRA" ADD CONSTRAINT "ORDEN_COMPRA_proveedor_id_PROVEEDOR_id_fkey" FOREIGN KEY ("proveedor_id") REFERENCES "PROVEEDOR"("id");--> statement-breakpoint
ALTER TABLE "ORDEN_COMPRA" ADD CONSTRAINT "ORDEN_COMPRA_sucursal_destino_SUCURSAL_id_fkey" FOREIGN KEY ("sucursal_destino") REFERENCES "SUCURSAL"("id");--> statement-breakpoint
ALTER TABLE "ORDEN_TRABAJO" ADD CONSTRAINT "ORDEN_TRABAJO_sucursal_id_SUCURSAL_id_fkey" FOREIGN KEY ("sucursal_id") REFERENCES "SUCURSAL"("id");--> statement-breakpoint
ALTER TABLE "ORDEN_TRABAJO" ADD CONSTRAINT "ORDEN_TRABAJO_receta_id_RECETA_id_fkey" FOREIGN KEY ("receta_id") REFERENCES "RECETA"("id");--> statement-breakpoint
ALTER TABLE "PEDIDO" ADD CONSTRAINT "PEDIDO_cliente_id_CLIENTE_id_fkey" FOREIGN KEY ("cliente_id") REFERENCES "CLIENTE"("id");--> statement-breakpoint
ALTER TABLE "PRODUCTO_LOTE" ADD CONSTRAINT "PRODUCTO_LOTE_orden_id_ORDEN_TRABAJO_id_fkey" FOREIGN KEY ("orden_id") REFERENCES "ORDEN_TRABAJO"("id");--> statement-breakpoint
ALTER TABLE "PRODUCTO" ADD CONSTRAINT "PRODUCTO_categoria_id_CATEGORIA_id_fkey" FOREIGN KEY ("categoria_id") REFERENCES "CATEGORIA"("id");--> statement-breakpoint
ALTER TABLE "PRODUCTO" ADD CONSTRAINT "PRODUCTO_unidad_medida_id_UNIDAD_MEDIDA_id_fkey" FOREIGN KEY ("unidad_medida_id") REFERENCES "UNIDAD_MEDIDA"("id");--> statement-breakpoint
ALTER TABLE "RECETA_DETALLE" ADD CONSTRAINT "RECETA_DETALLE_receta_id_RECETA_id_fkey" FOREIGN KEY ("receta_id") REFERENCES "RECETA"("id");--> statement-breakpoint
ALTER TABLE "RECETA_DETALLE" ADD CONSTRAINT "RECETA_DETALLE_materia_prima_id_MATERIA_PRIMA_id_fkey" FOREIGN KEY ("materia_prima_id") REFERENCES "MATERIA_PRIMA"("id");--> statement-breakpoint
ALTER TABLE "RECETA" ADD CONSTRAINT "RECETA_producto_id_PRODUCTO_id_fkey" FOREIGN KEY ("producto_id") REFERENCES "PRODUCTO"("id");--> statement-breakpoint
ALTER TABLE "SOLICITUD_INSUMO" ADD CONSTRAINT "SOLICITUD_INSUMO_sucursal_id_SUCURSAL_id_fkey" FOREIGN KEY ("sucursal_id") REFERENCES "SUCURSAL"("id");--> statement-breakpoint
ALTER TABLE "SOLICITUD_INSUMO" ADD CONSTRAINT "SOLICITUD_INSUMO_solicitado_por_USUARIO_id_fkey" FOREIGN KEY ("solicitado_por") REFERENCES "USUARIO"("id");--> statement-breakpoint
ALTER TABLE "STOCK_ALACENA" ADD CONSTRAINT "STOCK_ALACENA_alacena_id_ALACENA_id_fkey" FOREIGN KEY ("alacena_id") REFERENCES "ALACENA"("id");--> statement-breakpoint
ALTER TABLE "STOCK_ALACENA" ADD CONSTRAINT "STOCK_ALACENA_lote_id_LOTE_MATERIA_PRIMA_id_fkey" FOREIGN KEY ("lote_id") REFERENCES "LOTE_MATERIA_PRIMA"("id");--> statement-breakpoint
ALTER TABLE "STOCK_BODEGA" ADD CONSTRAINT "STOCK_BODEGA_bodega_id_BODEGA_id_fkey" FOREIGN KEY ("bodega_id") REFERENCES "BODEGA"("id");--> statement-breakpoint
ALTER TABLE "STOCK_BODEGA" ADD CONSTRAINT "STOCK_BODEGA_lote_id_LOTE_MATERIA_PRIMA_id_fkey" FOREIGN KEY ("lote_id") REFERENCES "LOTE_MATERIA_PRIMA"("id");--> statement-breakpoint
ALTER TABLE "SUCURSAL" ADD CONSTRAINT "SUCURSAL_municipio_id_MUNICIPIO_id_fkey" FOREIGN KEY ("municipio_id") REFERENCES "MUNICIPIO"("id");--> statement-breakpoint
ALTER TABLE "TURNO_DESPACHADOR" ADD CONSTRAINT "TURNO_DESPACHADOR_caja_id_CAJA_id_fkey" FOREIGN KEY ("caja_id") REFERENCES "CAJA"("id");--> statement-breakpoint
ALTER TABLE "TURNO_DESPACHADOR" ADD CONSTRAINT "TURNO_DESPACHADOR_usuario_id_USUARIO_id_fkey" FOREIGN KEY ("usuario_id") REFERENCES "USUARIO"("id");--> statement-breakpoint
ALTER TABLE "TURNO_DESPACHADOR" ADD CONSTRAINT "TURNO_DESPACHADOR_administrador_id_SUCURSAL_id_fkey" FOREIGN KEY ("administrador_id") REFERENCES "SUCURSAL"("id");